[libraries]
jackson-databind = "tools.jackson.core:jackson-databind:3.0.3"
jda = "net.dv8tion:JDA:6.1.0"
jna = "net.java.dev.jna:jna:5.18.1"
jreleaser = "org.jreleaser:org.jreleaser.gradle.plugin:1.20.0"
jspecify = "org.jspecify:jspecify:1.0.0"
junit = "org.junit.jupiter:junit-jupiter:5.14.0"
junit-launcher = "org.junit.platform:junit-platform-launcher:1.14.0"
slf4j = "org.slf4j:slf4j-api:2.0.17"
logback-classic = "ch.qos.logback:logback-classic:1.5.21"
zstd-jni = "com.github.luben:zstd-jni:1.5.7-6"

[bundles]
junit = [
    "junit",
    "junit-launcher",
]
