name: Test discord-zstd-java
on:
  pull_request:
  push:
    branches: [ master ]

env:
  COMMON_ZSTD_CMAKE_FLAGS: "-DZSTD_BUILD_PROGRAMS=OFF -DZSTD_LEGACY_SUPPORT=OFF -DZSTD_BUILD_STATIC=OFF -DBUILD_SHARED_LIBS=ON -DZSTD_BUILD_DICTBUILDER=OFF -DZSTD_BUILD_COMPRESSION=OFF -DCMAKE_BUILD_TYPE=Debug"
  COMMON_JNI_NATIVES_CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Debug"

jobs:
  build-zstd:
    name: Build Zstd
    runs-on: ubuntu-latest

    steps:
      - name: Clone zstd repo
        uses: actions/checkout@v5
        with:
          repository: facebook/zstd
          ref: "f8745da6ff1ad1e7bab384bd1f9d742439278e99" # v1.5.7

      - name: Build Zstd
        shell: bash
        run: |
          cd build/cmake
          mkdir -p ../../output/x64
          mkdir build-x64
          cd build-x64
          cmake $COMMON_ZSTD_CMAKE_FLAGS ..
          cmake --build . -j 4
          cp lib/libzstd.so ../../../output/x64/libzstd.so
          cd ..

      - name: Publish Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: zstd-ubuntu-latest
          path: output

  build-jni-natives:
    name: Build Zstd JNI natives
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Build discord-zstd-java-jni/natives
        shell: bash
        run: |
          mkdir -p output/x64
          cd jni-impl/natives
          mkdir build-x64
          cd build-x64
          cmake $COMMON_JNI_NATIVES_CMAKE_FLAGS ..
          cmake --build . -j 4
          cp libzstd-jni.so ../../../output/x64/libzstd.so
          cd ..

      - name: Publish Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: jni-natives-ubuntu-latest
          path: output

  test:
    name: Test discord-zstd-java
    runs-on: ubuntu-latest
    needs: [build-zstd, build-jni-natives]

    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          path: temp-zstd
          pattern: zstd-ubuntu-latest
          merge-multiple: true

      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          path: temp-jni-natives
          pattern: jni-natives-ubuntu-latest
          merge-multiple: true

      - name: Move Artifacts
        run: |
          mkdir -p natives/src/main/resources/natives/linux-x86-64
          mkdir -p jni-impl/src/main/resources/natives/linux-x86-64
          cp temp-zstd/x64/libzstd.so natives/src/main/resources/natives/linux-x86-64/libzstd.so
          cp temp-jni-natives/x64/libzstd.so jni-impl/src/main/resources/natives/linux-x86-64/libzstd.so

      - name: Run tests
        env:
          TEST_DATA_ZSTD_KEY: ${{ secrets.TEST_DATA_ZSTD_KEY }}
          TEST_DATA_ZSTD_PARAMETERS: ${{ secrets.TEST_DATA_ZSTD_PARAMETERS }}
        run: ./gradlew test

      - name: Upload JUnit XML Test Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: junit-xml-test-report
          path: '**/build/test-results/test'
          
      - name: Upload HTML Test Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: junit-html-test-report
          path: '**/build/reports/tests/test'
          
      - name: Annotate Failed Tests
        uses: mikepenz/action-junit-report@v6.0.0
        if: ${{ !cancelled() }}
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          annotate_only: 'true'
